package org.rui.model;

import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.persistence.Transient;
import java.util.Date;

@Data
@EqualsAndHashCode(callSuper = false)
public class User extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.salt
     *
     * @mbggenerated
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile_phone
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.has_lock
     *
     * @mbggenerated
     */
    private Boolean hasLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.has_del
     *
     * @mbggenerated
     */
    private Boolean hasDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.has_admin
     *
     * @mbggenerated
     */
    private Boolean hasAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_time
     *
     * @mbggenerated
     */
    private Date loginTime;

    @Transient
    private String roleName;

}